# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WinForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WinForm(object):
    def setupUi(self, WinForm):
        WinForm.setObjectName("WinForm")
        WinForm.resize(1000, 800)
        self.btn_open = QtWidgets.QPushButton(WinForm)
        self.btn_open.setGeometry(QtCore.QRect(830, 60, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_open.setFont(font)
        self.btn_open.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.btn_open.setObjectName("btn_open")
        self.btn_save = QtWidgets.QPushButton(WinForm)
        self.btn_save.setGeometry(QtCore.QRect(830, 130, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("background-color: rgb(80, 170, 53);")
        self.btn_save.setObjectName("btn_save")
        self.btn_clear = QtWidgets.QPushButton(WinForm)
        self.btn_clear.setGeometry(QtCore.QRect(830, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 255);")
        self.btn_clear.setObjectName("btn_clear")

        self.retranslateUi(WinForm)
        QtCore.QMetaObject.connectSlotsByName(WinForm)

    def retranslateUi(self, WinForm):
        _translate = QtCore.QCoreApplication.translate
        WinForm.setWindowTitle(_translate("WinForm", "Form"))
        self.btn_open.setText(_translate("WinForm", "导入图片"))
        self.btn_save.setText(_translate("WinForm", "保存图片"))
        self.btn_clear.setText(_translate("WinForm", "清空标注"))
