# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1000, 700)
        widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        widget.setStyleSheet("")
        self.pushButton1 = QtWidgets.QPushButton(widget)
        self.pushButton1.setGeometry(QtCore.QRect(570, 300, 75, 32))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.pushButton1.setObjectName("pushButton1")
        self.label1 = QtWidgets.QLabel(widget)
        self.label1.setGeometry(QtCore.QRect(570, 270, 181, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color: rgb(170, 0, 127);\n"
"background-color: rgb(255, 253, 190);")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(widget)
        self.label2.setGeometry(QtCore.QRect(570, 370, 164, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: rgb(170, 0, 127);\n"
"background-color: rgb(255, 253, 190);")
        self.label2.setObjectName("label2")
        self.pushButton2 = QtWidgets.QPushButton(widget)
        self.pushButton2.setGeometry(QtCore.QRect(570, 400, 75, 32))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(widget)
        self.pushButton3.setGeometry(QtCore.QRect(800, 550, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 255);")
        self.pushButton3.setObjectName("pushButton3")
        self.listView = QtWidgets.QListView(widget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.listView.setStyleSheet("background-image: url(:/images/background.png);")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.pushButton3.raise_()
        self.label1.raise_()
        self.label2.raise_()
        self.pushButton2.raise_()
        self.pushButton1.raise_()
        self.label1.setBuddy(self.pushButton1)
        self.label2.setBuddy(self.pushButton2)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "基于人工智能的诊断软件系统"))
        self.pushButton1.setText(_translate("widget", "确定"))
        self.label1.setText(_translate("widget", "癌前病变诊断系统"))
        self.label2.setText(_translate("widget", "早癌EGC诊断系统"))
        self.pushButton2.setText(_translate("widget", "确定"))
        self.pushButton3.setText(_translate("widget", "退出检测"))
import apprcc_rc
